'use strict';
const themeSelect=document.querySelector('#theme');
try{const saved=localStorage.getItem('widehue-theme');if(['light','dark','purple','yellow'].includes(saved)){document.documentElement.dataset.theme=saved;themeSelect.value=saved;}}catch{}
themeSelect.addEventListener('change',()=>{document.documentElement.dataset.theme=themeSelect.value;try{localStorage.setItem('widehue-theme',themeSelect.value);}catch{}});
let toastTimeout;function notify(message){const toast=document.querySelector('#toast');toast.textContent=message;toast.classList.add('visible');clearTimeout(toastTimeout);toastTimeout=setTimeout(()=>toast.classList.remove('visible'),2600);}
async function copy(text){try{if(navigator.clipboard&&window.isSecureContext){await navigator.clipboard.writeText(text);}else{const field=document.createElement('textarea');field.value=text;field.style.cssText='position:fixed;left:-9999px';document.body.append(field);field.select();const ok=document.execCommand('copy');field.remove();if(!ok)throw Error('copy');}notify('Skopiowano do schowka');}catch{notify('Nie udało się skopiować. Zaznacz i skopiuj tekst ręcznie.');}}
document.querySelectorAll('[data-copy]').forEach(button=>button.addEventListener('click',()=>copy(button.dataset.copy)));
document.querySelector('#copy-starter').addEventListener('click',()=>copy(document.querySelector('#starter-code').textContent));
document.querySelector('#demo-form').addEventListener('submit',event=>{event.preventDefault();const name=new FormData(event.currentTarget).get('team').trim();const result=document.querySelector('#form-result');result.textContent=name?`Gotowe, ${name}! Formularz działa. Niczego nie wysłano.`:'Podaj nazwę zespołu inną niż same spacje.';});
const links=[...document.querySelectorAll('nav a')];const observer=new IntersectionObserver(entries=>{const visible=entries.filter(entry=>entry.isIntersecting).sort((a,b)=>a.boundingClientRect.top-b.boundingClientRect.top);if(!visible.length)return;links.forEach(link=>{if(link.hash==='#'+visible[0].target.id)link.setAttribute('aria-current','location');else link.removeAttribute('aria-current');});},{rootMargin:'-5% 0px -65% 0px',threshold:0});document.querySelectorAll('main section[id]').forEach(section=>observer.observe(section));
